// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CropFormController from "./crop_form_controller"
application.register("crop-form", CropFormController)

import FilterPlannedCropsController from "./filter_planned_crops_controller"
application.register("filter-planned-crops", FilterPlannedCropsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TurboformController from "./turboform_controller"
application.register("turboform", TurboformController)
import ThreejsController from "./threejs_controller"
application.register("threejs", ThreejsController)

import CropForm from "./crop_form_controller"
application.register("crop-form", CropForm)
