SUMMER_VEG_ARRAY = [
  'Beans',
  'Beetroots',
  'Broccolis',
  'Brussel Sprouts',
  'Cabbages',
  'Carrots',
  'Chillies',
  'Chives',
  'Corn',
  'Cucumbers',
  'Eggplants',
  'Fennel bulbs',
  'Leeks',
  'Lettuces',
  'Mustard Greens',
  'Okras',
  'Onions',
  'Parsnips',
  'Pumpkins',
  'Radishes',
  'Rhubarb (crowns)',
  'Rockmelons',
  'Shallots',
  'Tomatoes',
  'Turnips',
  'Watermelons',
  'Zucchinis'
]

AUTUMN_VEG_ARRAY = [
  'Beetroots',
  'Broad Beans',
  'Broccolis',
  'Brussel Sprouts',
  'Cabbages',
  'Carrots',
  'Cauliflowers',
  'Chives',
  'Fennels',
  'Garlic bulbs',
  'Jerusalem Artichokes',
  'Leeks',
  'Lettuces',
  'Mustard Greens',
  'Onions',
  'Parsnips',
  'Peas',
  'Radishes',
  'Shallot',
  'Siverbeet',
  'Snow Peas',
  'Spinach leaves',
  'Swedes',
  'Turnips',
  'Womboks'
]

WINTER_VEG_ARRAY = [
  'Artichokes',
  'Asparagus',
  'Beetroots',
  'Broad Beans',
  'Cabbages',
  'Garlic bulbs',
  'Jerusalem Artichokes',
  'Leeks',
  'Lettuces',
  'Mustard Greens',
  'Onions',
  'Parsnips',
  'Peas',
  'Potatoes',
  'Radishes',
  'Rhubarb (crowns)',
  'Shallots',
  'Snow Peas',
  'Spinach leaves',
  'Spring Onions',
  'Tomatoes',
  'Watermelons'
]

SPRING_VEG_ARRAY = [
  'Artichokes',
  'Asparagus',
  'Beans',
  'Beetroots',
  'Broccolis',
  'Cabbages',
  'Capsicums',
  'Carrots',
  'Celeries',
  'Chillies',
  'Chives',
  'Cucumbers',
  'Eggplants',
  'Fennel bulbs',
  'Garlic bulbs',
  'Jerusalem Artichokes',
  'Leeks',
  'Lettuces',
  'Mustard Greens',
  'Okras',
  'Parsnips',
  'Peas',
  'Potatoes',
  'Pumpkins',
  'Radishes',
  'Rhubarb (crowns)',
  'Rockmelons',
  'Shallots',
  'Snow Peas',
  'Spinach leaves',
  'Spring Onions',
  'Squashes',
  'Sunflowers',
  'Swedes',
  'Corn',
  'Tomatoes',
  'Turnips',
  'Watermelons',
  'Womboks',
  'Zucchinis'
]
